<script type="text/javascript" src="/js/flowplayer-3.2.6.min.js"></script>
<section id="casts">
    <div class="page-header"><h1>Title of Casts</h1></div>
    <div class="row">
        <div class="span11">
            <a href="/casts/sample.mov"
               style="z-index:1;display:block;width:640px;height:390px;margin-bottom:9px;"
               id="player">
            </a>
            <!-- this will install flowplayer inside previous A- tag. -->
            <script>flowplayer("player", "/swf/flowplayer-3.2.7.swf");</script>
        </div>
    </div>
    <div class="row">
        <div class="span11">
            <p>Write an awesome description here about how cool this cast is how it will help you out.</p>
        </div>
    </div>
</section>