<div class="page-header"><h1>Terms of Use</h1></div>
<h2>Building a Relationship</h2>
<p>Accessing and using our products, you agree to comply with Terms of Use listed
    here as well as our Privacy Policy.</p>
<p>By doing the absolute best to provide you with a quality product. You agree to
    refrain from activity that prohibits or inhibits us from providing these products to you.</p>
<p>Using our products, you agree to access them through our interface and will not
    attempt to circumvent the system.</p>
<p>We reserve the right to terminate your account or stop providing products and
    services should you violate our Terms of Use. While we hope this never happens,
    it's important that you know we reserve the right to do it.</p>
<p>Likewise, if you decide you no longer want to use our products, you can terminate
    our agreement at any time by closing your account.</p>

<h2>Take Responsibility</h2>
<p>Be responsible. We will not be liable for decisions you make or your actions 
    beyond the scope of our products. Every action has a re-action.</p>
<p>Our products are for your personal use. We work really hard to provide you 
    with a quality product and expect that you won't try to resell, copy, or
    make our products available to others without our written permission.
    If you love our product enough to pass it along, please just ask us.</p>
<p>It is your responsibility to keep your contact and registration information up to date.
    If you don't tell us when something changes, we won't know about it.</p>
<p>You are responsible for the safekeeping of your login and password. 
    Account activity is your responsibility, so we suggest keeping this information
    in a safe place.</p>

<h2>Providing Service</h2>
<p>Our intention is to consistently add to and improve our products.
    We may update, add, or remove products without prior notice to you.</p>
<p>We strive to provide you with an exceptional customer experience and are
    always open to suggestions, comments, and feedback.</p>
<p>We want you to have fun and hopefully learn something great while using our products,
    however we don't guarantee this will happen.</p>
<p>We work diligently to make sure our products are available and reliable.
    Because of the nature of our business, this is not something we can always control or guarantee.</p>