<!DOCTYPE html>
<html>
    <head>
        <title>code-casts.com</title>
        <link rel="stylesheet" href="/css/doc.css">
        <link rel="stylesheet" href="/css/bootstrap.css">
    </head>
    <body>
        <div class="topbar">
            <div class="topbar-inner">
                <div class="container">
                    <a class="brand" href="/">{Code-Casts}</a>
                </div>
            </div>
        </div>
        <div id="body" class="container">
            <?php echo $this->layout()->content; ?>
        </div>
        <footer class="footer">
            <div class="container">
                <p>
                    <a href="/terms-of-use">Terms of Use</a> |
                    <a href="/privacy-policy">Privacy Policy</a> |
                    <a href="/about">About</a>
                </p>
            </div>
        </footer>
    </body>
</html>
