<div class="page-header"><h1>About</h1></div>

<h2>The Problem</h2>
<p>Having to hire and train a large amount of developers, has shown a lake of
good tools to help hire, train, and grow developers. So we started code-casts.com, a
site designed to help you either prepare you for a job in the software field, or hire the
best when you need to grow your staff.</p>

<h2>The Solution</h2>
<p>Create a learning platform that allows for developers of all skills, and
    programming languages to learn and develop. Materials range for beginner to
    advanced and allow you learn and measure your skills as they grow.</p>
<p>Screencasts can be anywhere from 10-20 minutes, and are either part of a series or
    providing you with the skills to take on a related challenge.</p>

<h2>The Team</h2>
<p>Code Casts was started by the guys at Level 84. Who have been developing,
    managing, and training staff at some of the largest Websites in the world.</p>