<div class="page-header"><h1>About</h1></div>

<h2>The Problem</h2>
<p>Having hired and trained a large number of developers recently has exposed a severe lack of
good tools to help with this process, so we started code-casts.com!
This site is designed to help software developers prepare for their next job, as well as enable the software recruiter / 
trainer needing to acquire and develop their staff.</p>

<h2>The Solution</h2>
<p>Create a learning platform that allows for developers of all skills and
    programming languages to learn and develop effectively. Materials range from beginner to
    advanced and allow you learn and measure your skills as they grow.</p>
<p>Screencasts can range in duration from 10-20 minutes, can be standalone or part of a series.
    All will provide you with fundamental skills you will need to take on your next coding challenge.</p>

<h2>The Team</h2>
<p>Code-Casts was started by the guys at <a href="http://www.level84.com">Level 84</a>, who have been developing,
    managing, and training staff at some of the largest websites and software development shops in the world.</p>