<h1>Privacy Policy</h1>
<p>Privacy Policy applies to all services and products offered by code-casts.com.</p>
<h2>Using</h2>
<p><strong>Information you provide</strong> - If you sign up or use our products, we might
    request personal information from you. This information will not sold to
    others, though we may use it to offer you additional products, promotions, or
    improve future features.</p>
<p><strong>Communications</strong> - Communicate with Code Cast, by email or other
    means, will be stored. This will allow us to improve internal training, responses
    to your inquiries, suggestions, or the quality of our product.</p>

<h2>Sharing</h2>
<p>We will not share your sensitive information, enforced by applicable laws or we have your permission.</p>
<p>Should Code Casts ever merge with, acquire, or be sold to another company,
    a notification will be sent prior to transfer of information and subjected to a different Privacy Policy.

<h2>Security</h2>
<p>Since you provide us with sensitive information, we take ever measure possible
    to protect your information against unauthorized access or disclosure.
    Access to your information is restricted to employees or contractors of
    Envy Labs who are bound by confidentiality obligations and non-disclosure agreements.</p>

<h2>Changes</h2>
<p>If something significant changes with our Privacy Policy we will notify you.</p>